name: Backend Deploy To Home Server
on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    types: [opened, closed]
    paths:
      - 'back/**'
jobs:
  Check_Path:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for backend changes
        id: check
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin main
            CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
          else
            CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD)
          fi
          echo "Changed files:"
          echo "$CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q "^back/"; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  Deploy:
    needs: Check_Path
    if: |
      needs.Check_Path.outputs.should_deploy == 'true' && 
      (github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: SSH로 홈서버 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.HOME_SERVER_HOST }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          password: ${{ secrets.HOME_SERVER_PASSWORD }}
          port: ${{ secrets.HOME_SERVER_PORT }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            # Docker 권한 확인 및 설정
            if ! groups $USER | grep -q docker; then
              sudo usermod -aG docker $USER
              newgrp docker
            fi
            
            # 프로젝트 디렉토리로 이동
            cd /home/ubuntu/moya/back/moya
            
            # 로컬 변경사항 초기화
            git reset --hard
            git clean -fd
            
            # git pull
            git remote set-url origin git@github.com:sungwon2598/moya.git
            git pull origin main
            
            # application.yml 생성
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            
            # Dockerfile 생성
            echo 'FROM eclipse-temurin:21-jdk AS builder
            WORKDIR /app
            COPY . .
            RUN chmod +x ./gradlew
            RUN ./gradlew clean build -x test

            FROM eclipse-temurin:21-jre
            WORKDIR /app
            COPY --from=builder /app/build/libs/*SNAPSHOT.jar app.jar
            ENV JAVA_OPTS="-Xms128m -Xmx256m -XX:+UseSerialGC -XX:MaxHeapFreeRatio=70 -XX:MinHeapFreeRatio=40 -XX:+UseStringDeduplication -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/heapdump.hprof"
            EXPOSE 8080
            ENTRYPOINT ["sh", "-c", "java \$JAVA_OPTS -jar app.jar"]' > Dockerfile
            
            # docker-compose.yml 생성
            cd /home/ubuntu/moya-docker
            echo 'version: "3.8"

            services:
              mysql:
                image: mysql:8.0
                container_name: moya-mysql
                environment:
                  MYSQL_ROOT_PASSWORD: Seoil7345!
                  MYSQL_DATABASE: teams
                  MYSQL_USER: moyastudy
                  MYSQL_PASSWORD: Seoil7345!
                ports:
                  - "3306:3306"
                volumes:
                  - mysql-data:/var/lib/mysql
                command:
                  - --character-set-server=utf8mb4
                  - --collation-server=utf8mb4_unicode_ci
                restart: always
                networks:
                  - moya-network

              redis:
                image: redis:latest
                container_name: moya-redis
                command: redis-server --requirepass Seoil7345!
                ports:
                  - "6379:6379"
                volumes:
                  - redis-data:/data
                restart: always
                networks:
                  - moya-network

              springboot-app:
                build:
                  context: /home/ubuntu/moya/back/moya
                  dockerfile: Dockerfile
                container_name: moya-springboot
                ports:
                  - "8080:8080"
                environment:
                  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/teams
                  SPRING_DATA_REDIS_HOST: redis
                volumes:
                  - /home/ubuntu/moya/back/moya/logs:/app/logs
                  - /home/ubuntu/moya/back/moya/heapdump:/app/heapdump
                depends_on:
                  - mysql
                  - redis
                restart: always
                networks:
                  - moya-network

            volumes:
              mysql-data:
              redis-data:

            networks:
              moya-network:
                driver: bridge' > docker-compose.yml
            
            # 디렉토리 생성
            mkdir -p /home/ubuntu/moya/back/moya/{logs,heapdump}
            
            # Docker Compose 실행 (이전 컨테이너 중지 후 새로 빌드)
            cd /home/ubuntu/moya-docker
            docker-compose down || true
            docker-compose up -d --build

  Notify:
    needs: [Check_Path, Deploy]
    if: always() && needs.Check_Path.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            MESSAGE="백엔드 코드가 main 브랜치에 푸시되었습니다.\n\n커밋 메시지: ${{ github.event.head_commit.message }}"
          elif [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.action }}" = "opened" ]; then
            MESSAGE="백엔드 코드의 새로운 PR이 생성되었습니다.\n\nPR 번호: #${{ github.event.pull_request.number }}\n\nPR 제목: ${{ github.event.pull_request.title }}"
          elif [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            MESSAGE="백엔드 코드 PR이 main 브랜치에 병합되었습니다.\n\nPR 번호: #${{ github.event.pull_request.number }}\n\nPR 제목: ${{ github.event.pull_request.title }}"
          else
            MESSAGE="백엔드 배포 워크플로우가 실행되었습니다."
          fi
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
