name: Backend Deploy To EC2 Server (Session Manager)
on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    types: [opened, closed]
    paths:
      - 'back/**'

# OIDC 토큰을 위한 권한 설정
permissions:
  id-token: write
  contents: read

jobs:
  Check_Path:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for backend changes
        id: check
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin main
            CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
          else
            CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD)
          fi
          echo "Changed files:"
          echo "$CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q "^back/"; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  Deploy:
    needs: Check_Path
    if: |
      needs.Check_Path.outputs.should_deploy == 'true' && 
      (github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # OIDC로 AWS 인증 (GitHub Secrets 불필요!)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::179227986066:role/GitHubActionsRole
          aws-region: ap-northeast-2

      # Parameter Store에서 설정 정보 가져오기
      - name: Get parameters from AWS Parameter Store
        run: |
          echo "INSTANCE_ID=$(aws ssm get-parameter --name "/moya/backend/server/instance-id" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          
          APPLICATION_PROPERTIES=$(aws ssm get-parameter --name "/moya/backend/application-yml" --with-decryption --query "Parameter.Value" --output text)
          
          # 환경 변수로 설정 (멀티라인 텍스트)
          echo "APPLICATION_PROPERTIES<<EOF" >> $GITHUB_ENV
          echo "$APPLICATION_PROPERTIES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Session Manager로 배포 명령 실행
      - name: Deploy via Session Manager
        run: |
          # APPLICATION_PROPERTIES를 파일로 저장
          echo "$APPLICATION_PROPERTIES" > application.yml
          
          # Session Manager로 명령 실행
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "echo \"=== Starting deployment process ===\"",
              "echo \"Current directory: $(pwd)\"",
              "cd /home/ubuntu/moya/back/moya",
              "echo \"Changed to directory: $(pwd)\"",
              "echo \"=== Fixing Git ownership ===\"",
              "sudo chown -R ubuntu:ubuntu /home/ubuntu/moya",
              "git config --global --add safe.directory /home/ubuntu/moya",
              "sudo git config --global --add safe.directory /home/ubuntu/moya/back/moya",
              "echo \"Git ownership fixed\"",
              "echo \"=== Current state before update ===\"",
              "echo \"Current commit BEFORE pull: $(git rev-parse HEAD)\"",
              "echo \"Current branch: $(git branch --show-current)\"",
              "echo \"=== Git reset hard ===\"",
              "git reset --hard",
              "echo \"Git reset completed\"",
              "echo \"=== Git clean ===\"",
              "sudo git clean -fd -e logs/",
              "echo \"Git clean completed\"",
              "echo \"=== Setting remote URL ===\"",
              "git remote set-url origin https://github.com/sungwon2598/moya.git",
              "echo \"Remote URL set to: $(git remote get-url origin)\"",
              "echo \"=== Fetching latest changes ===\"",
              "git fetch origin main",
              "echo \"Fetch completed\"",
              "echo \"=== Git pull ===\"",
              "git pull origin main",
              "echo \"=== Verifying update ===\"",
              "echo \"Current commit AFTER pull: $(git rev-parse HEAD)\"",
              "echo \"Latest commits:\"",
              "git log --oneline -5",
              "git status",
              "echo \"=== Stopping existing Java processes ===\"",
              "sudo pkill -f \"java.*moya.*jar\" || echo \"No existing Java processes found\"",
              "echo \"Waiting for processes to stop...\"",
              "sleep 3",
              "echo \"=== Setting gradlew permissions ===\"",
              "sudo chmod +x ./gradlew",
              "echo \"Gradlew permissions set. File info: $(ls -la ./gradlew)\"",
              "echo \"=== Starting build process ===\"",
              "sudo ./gradlew clean build -x test",
              "echo \"Build completed. Checking build artifacts:\"",
              "ls -la build/libs/",
              "echo \"=== Starting application ===\"",
              "nohup java -Xmx256m -jar build/libs/moya-0.0.1-SNAPSHOT.jar > app.log 2>&1 &",
              "sleep 5",
              "echo \"=== Checking application status ===\"",
              "if pgrep -f \"java.*moya.*jar\" > /dev/null; then echo \"✅ Application started successfully. PID: $(pgrep -f java.*moya.*jar)\"; else echo \"❌ Application failed to start\" && exit 1; fi",
              "echo \"=== Final verification ===\"",
              "echo \"Deployed commit: $(git rev-parse HEAD)\"",
              "echo \"Deployed at: $(date)\"",
              "echo \"=== Deployment process completed ===\""
            ]' \
            --query "Command.CommandId" --output text)
          
          echo "Command ID: $COMMAND_ID"
          
          # 명령 실행 완료 대기 (최대 10분)
          echo "Waiting for command execution to complete..."
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --cli-read-timeout 600 \
            --cli-connect-timeout 60
          
          # 실행 결과 확인
          echo "Command execution result:"
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query 'Status'
          
          # 상세 로그 출력 (성공/실패 관계없이)
          echo "=== Standard Output ==="
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query 'StandardOutputContent' --output text
          
          echo "=== Standard Error ==="
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query 'StandardErrorContent' --output text
          
          # 성공 여부 확인
          STATUS=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query 'Status' --output text)
          
          if [ "$STATUS" != "Success" ]; then
            echo "Deployment failed with status: $STATUS"
            exit 1
          fi
          
          echo "Deployment completed successfully!"